### ISSUE TITLE
Combining OBIS and MPA visualization

### ISSUE THREAD

**Issue by microlei** [oceanhackweek/ohw20-proj-species-marine-protected-areas#36]
- [ ] Color MPAs by number of OBIS entries
- [ ] Fetch OBIS entries based on selection of MPAs
- [ ] Statistics of fetched OBIS entries

**Comment by eqmh** [comment]
[obis_mpa_sel_country.Rmd](https://github.com/oceanhackweek/ohw20-proj-species-marine-protected-areas/blob/master/obis_mpa_sel_country.Rmd) gets these three things done. 

The output is an interactive map showing MPAs for a selected country color coded according to number of OBIS records. Clicking the provides the WDPAID and the number of OBIS records.
<img width="685" alt="Screen Shot 2021-08-06 at 10 43 52 AM" src="https://user-images.githubusercontent.com/20710865/128528140-12f90e46-535d-4163-b45b-9800b8474ff1.png">


This issue can now be closed, I think.
